export const FETCH_CHARACTER_LIST_START = "FETCH_CHARACTER_LIST_START";
export const FETCH_CHARACTER_LIST_SUCCESS = "FETCH_CHARACTER_LIST_SUCCESS";
export const FETCH_CHARACTER_LIST_FAIL = "FETCH_CHARACTER_LIST_FAIL";

export const RESET_CHARACTER_STORE = "RESET_CHARACTER_STORE";

export type CharacterActionTypes =
  | typeof FETCH_CHARACTER_LIST_START
  | typeof FETCH_CHARACTER_LIST_SUCCESS
  | typeof FETCH_CHARACTER_LIST_FAIL
  | typeof RESET_CHARACTER_STORE;
